In [2]:
import numpy as np
#Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.#Create  

array = np.random.rand(10,1);
print(array);

np.mean(array)

[[0.11963142]
 [0.4147223 ]
 [0.05364568]
 [0.47851703]
 [0.98245058]
 [0.18107865]
 [0.81840225]
 [0.39136554]
 [0.91300767]
 [0.45290594]]


0.48057270732165513

In [3]:
#Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

array1 = np.random.rand(20,1)
print(array1)

[[0.98549848]
 [0.61055348]
 [0.31869549]
 [0.3785756 ]
 [0.7269726 ]
 [0.07082168]
 [0.16734374]
 [0.59941061]
 [0.64589321]
 [0.11157389]
 [0.30691677]
 [0.96985255]
 [0.42406415]
 [0.37329121]
 [0.01879654]
 [0.91536447]
 [0.65893081]
 [0.61669931]
 [0.27730724]
 [0.06585253]]


In [4]:
# Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

A = np.random.rand(10,20)
B = np.random.rand(20,25)

C = np.matmul(A,B)
print(C)

[[4.76154583 4.63401853 5.09452704 5.03614466 4.91159389 5.80267157
  5.34407191 5.1822865  6.61615382 4.40938587 5.04112592 4.39083199
  6.25288553 4.45297214 6.65163923 4.40481413 4.42168733 5.41354382
  4.64714492 5.20310724 3.81934012 4.72382921 5.23457805 5.1195981
  5.97314772]
 [4.50827093 4.1298574  4.30202944 4.8825257  5.0123045  5.34284382
  4.38003941 4.55797463 5.16912796 3.26626613 4.56373168 3.86903888
  4.82514967 3.97836438 5.97290118 3.50105314 3.9626016  4.61444897
  3.69483042 4.76370883 3.08176624 3.61846573 4.89655814 4.06439738
  4.35506616]
 [4.48825452 4.41069459 3.66367627 5.2295804  4.98784949 4.59076682
  4.80953475 4.96293928 5.50776727 3.65386595 4.92761781 4.50688417
  5.38425651 4.44458625 5.695399   3.77770522 4.40151355 4.53424143
  3.90524428 4.19590823 3.56549748 4.90734316 4.63617563 4.61406856
  5.11216066]
 [3.78177795 3.90311029 3.30276457 4.07075665 4.53363582 4.03032931
  3.65071948 4.60065962 4.60855997 3.08623519 3.77587666 3.221459
  4.09913

In [5]:
# Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

#f(x)=1 / (1 + exp(-x)) 
#Apply this function to each element of A and print the new array holding the value the function returns
#Example:

#a=[a1,a2,a3]   
#n(new array to be printed )=[ f(a1), f(a2), f(a3)]

A = np.random.rand(10,1)
print (A)

def func(x):
    return (1 / (1 + np.exp(-x)))
    
function = np.apply_along_axis(func, 0, A)
print(function)

[[0.16536857]
 [0.36783705]
 [0.12337847]
 [0.05677631]
 [0.87542365]
 [0.36904647]
 [0.2587535 ]
 [0.85249213]
 [0.24654452]
 [0.78551492]]
[[0.54124818]
 [0.59093623]
 [0.53080555]
 [0.51419027]
 [0.70587299]
 [0.59122855]
 [0.56432985]
 [0.70108966]
 [0.56132581]
 [0.68686749]]
